name: Launch Grading PR
on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  create-and-trigger:
    runs-on: ubuntu-latest
    env:
      BLANK_BRANCH: grading-blank
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Determine default branch
        id: def
        run: echo "DEF=${{ github.event.repository.default_branch }}" >> "$GITHUB_OUTPUT"

      - name: Create/update blank base branch (shares history)
        run: |
          set -euo pipefail
          DEF="${{ steps.def.outputs.DEF }}"
          # Create or reset grading-blank *from* the default branch (shared history)
          if git ls-remote --exit-code --heads origin "$BLANK_BRANCH" >/dev/null 2>&1; then
            git fetch origin "$BLANK_BRANCH":"$BLANK_BRANCH" || true
            git checkout -B "$BLANK_BRANCH" "origin/$BLANK_BRANCH" || git checkout -B "$BLANK_BRANCH" "$DEF"
            git reset --hard "$DEF"
          else
            git checkout -B "$BLANK_BRANCH" "$DEF"
          fi

          # Remove everything on grading-blank and commit a minimal empty baseline
          git rm -r -q --cached .
          git clean -fdx
          echo "Grading base" > .grading_base
          git add -A
          git -c user.name="github-actions" -c user.email="actions@github.com" commit -m "Grading base (empty)"
          # Force-push so the blank base always reflects latest DEF ancestry
          git push -f origin "$BLANK_BRANCH"


      - name: Create (or find) grading PR
        id: pr
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -euo pipefail
          DEF="${{ steps.def.outputs.DEF }}"
          # Find existing PR DEF -> BLANK
          PR_NUM=$(gh pr list --base "$BLANK_BRANCH" --head "$DEF" --json number -q '.[0].number' || true)
          if [ -z "${PR_NUM:-}" ]; then
            TITLE="Grading PR: ${DEF} → ${BLANK_BRANCH}"
            BODY="Automated grading PR comparing the full repo to a blank base."
            PR_URL=$(gh pr create --base "$BLANK_BRANCH" --head "$DEF" --title "$TITLE" --body "$BODY")
            PR_NUM=$(gh pr view --json number -q .number)
          else
            PR_URL=$(gh pr view "$PR_NUM" --json url -q .url)
          fi
          echo "number=$PR_NUM" >> "$GITHUB_OUTPUT"
          echo "url=$PR_URL"    >> "$GITHUB_OUTPUT"

      - name: Trigger AI review via comment
        if: ${{ steps.pr.outputs.number != '' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr comment ${{ steps.pr.outputs.number }} -b "/review"

      - name: Output link
        if: ${{ steps.pr.outputs.url != '' }}
        env:
          PR_URL: ${{ steps.pr.outputs.url }}
        run: |
          echo "PR link: $PR_URL"
          echo "::notice title=Grading PR::$PR_URL"
